services:
  frontend:
    build: 
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/frontend
    tty: true
    ports:
      - "5173:5173"
      - "4173:4173"

  backend:
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/backend
    tty: true
    ports:
      - "5555:5555"  # ホストのポート5555をコンテナのポート5555にフォワーディング
      - "5001:5001"  # Firebase Functions のデフォルトポート
      - "4000:4000"  # Firebase Emulator UI のポート
      - "9099:9099"  # Firebase Auth のポート
